---
AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to Create Security Group Settings.

Parameters:
  VpcId:
    Description: ID of VPC
    Type: AWS::EC2::VPC::Id

Resources:
  GlueSelfRerencingSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      VpcId:
        Ref: VpcId  
      GroupDescription: Database Security Group for AWS Glue Study
      Tags: 
        - Key: Name
          Value: AWSGlueStudySelfRerencingSecurityGroup
  SelfRerencingSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId:
        Ref: GlueSelfRerencingSecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId:
        Ref: GlueSelfRerencingSecurityGroup
  SSHSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId:
        Ref: GlueSelfRerencingSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0
  HttpsSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      GroupId:
        Ref: GlueSelfRerencingSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0
  SelfRerencingSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties: 
      GroupId:
        Ref: GlueSelfRerencingSecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      DestinationSecurityGroupId:
        Ref: GlueSelfRerencingSecurityGroup
  PublicSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties: 
      GroupId:
        Ref: GlueSelfRerencingSecurityGroup
      IpProtocol: -1
      CidrIp: 0.0.0.0/0